### ISSUE TITLE
Need more robust algorithm for random placement of objects in the scene subject[fridge]

### ISSUE THREAD

**Issue by bytes-as** [fellowship/Fridge-Food-Type#4]
Current version:
 - pick a object that is allowed to change places
 - check its allowance for rotation along different axis, apply transformation accordingly
 - get the possible location from uniform probability distribution from the allowed locations
 - __check if the object is overlapping with any other object in 3d space__ 

https://github.com/fellowship/Fridge-Food-Type/blob/5b460ed14df382ed499d9a639c1faab791f651a6/Blender/blender_automation/src/render_poses.py#L36

https://github.com/fellowship/Fridge-Food-Type/blob/5b460ed14df382ed499d9a639c1faab791f651a6/Blender/blender_automation/src/RenderInterface.py#L125-L137

https://github.com/fellowship/Fridge-Food-Type/blob/5b460ed14df382ed499d9a639c1faab791f651a6/Blender/blender_automation/src/BlenderAPI/BlenderObject.py#L93-L128

Issue : 
- Because each object is needed to check against every other object in the scene, the time taken by the whole process went to time complexity of O(n^2)

-------
- [_incomplete_]No need to check the objects which aren't inside the fridge, so before checking the intersection we need to check if the object in question is even in the fridge or not
- Instead of systematically choosing a object, then finding a random place, we could go the other way around, choosing systematically a location for a randomly chosen object [_implementation could get messy_]
     - Obviously we need to form some sort of grid like structure on the platform where the object are going to be placed, but in this case there would be not checking for overlapping or any of that sort.
     - That grid would require to have dynamic allocation of space for different objects
 - [_incomplete/Later stage_] Instead of importing all the models and import a set(select with uniform probability) of objects and generate a fixed number of images with that set of selected objects, before re-selecting those objects based uniform probability again.

**Comment by Nickleha** [comment]
I'm fiddling around with it still. I think envisioning every shelf as a separate 2d space and only doing bounding box (both placement and intersection checks) calculations should be much faster

**Comment by bytes-as** [comment]
It would definitely improve the performance, will add that bounding box `isIntersecting` module

**Comment by Nickleha** [comment]
I think I want to wait to see the runtime on an image for bounding box intersection checks but still random placement. Any better automatic placement will generally give priority to filling from a certain region (like top left).  There are ways to work around having those creating too similar of images (object shuffling prior to placement), but it still seems like it will make image variety suffer somewhat

**Comment by Nickleha** [comment]
I think our runtime should be fine if we 
1) only check on objects already placed on shelf this object is trying to join
    1a) store list of items on each shelf per image shuffling
2) do intersection checks via bounding box

I haven't looked through this too much, but this may be helpful for us
https://github.com/secnot/rectpack

and one extra thing that may be useful if we go to an algorithmic placing approach
https://www.codeproject.com/Articles/210979/Fast-optimizing-rectangle-packing-algorithm-for-bu:

**Comment by bytes-as** [comment]
I have added the intersection check over Bounding boxes, here is the PR #5

**Comment by Nickleha** [comment]
I'm closing this. Placement isn't perfect, but we're on runtimes <1s for object placement most of the time. Perfectly fine given how long rendering takes.
